default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: dmytro

development:
  <<: *default
  database: teafans_dev

test:
  <<: *default
  database: teafans_test

production:
  <<: *default
  database: railway_production
  url: <%= ENV["DATABASE_URL"] %>
  username: railwayapp
  password: <%= ENV["RAILWAYAPP_DATABASE_PASSWORD"] %>


